### ISSUE TITLE
Command failed

### ISSUE THREAD

**Issue by allthesignals** [poetic/ember-cli-github-pages#61]
Not sure why but I can't deploy again:

```
Command failed: git -c core.safecrlf=false add "." && git commit -m "Initial gh-pages second"

Error: Command failed: git -c core.safecrlf=false add "." && git commit -m "Initial gh-pages second"

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by allthesignals** [comment]
Does anyone know what this error is even saying?

**Comment by knownasilya** [comment]
Did you recently update the addon? If not can you try that, if so can you see if the previous version works?

**Comment by Alex-Aralis** [comment]
I'm also getting this issue on 0.2.0, but only when `ember build && ember github-pages:commit --message \"Deploy gh-pages from commit $(git rev-parse HEAD)\" && git push origin gh-pages:gh-pages` is run from the `package.json` scripts.  Issue persists after reverting to 0.1.3.

**Comment by amk221** [comment]
I'm also getting this with 0.2.0

```
Command failed: git -c core.safecrlf=false add "." && git commit -m "rebuild"
```


<details>
=================================================================================

ENV Summary:

  TIME: Thu Oct 04 2018 10:36:27 GMT+0100 (BST)
  TITLE: ember
  ARGV:
  - /Users/andrew/.nodenv/versions/8.11.4/bin/node
  - /Users/andrew/.nodenv/versions/8.11.4/bin/ember
  - github-pages:commit
  - --message
  - rebuild
  EXEC_PATH: /Users/andrew/.nodenv/versions/8.11.4/bin/node
  TMPDIR: /var/folders/kc/h72gxdjd6ys_d0psnc0k3brh0000gn/T
  SHELL: /bin/zsh
  PATH:
  - /Users/andrew/.nodenv/versions/8.11.4/bin
  - /usr/local/Cellar/nodenv/1.1.2/libexec
  - /Users/andrew/.yarn/bin
  - /Users/andrew/.local/bin
  - /Users/andrew/.jenv/shims
  - /Users/andrew/.nodenv/shims
  - /Users/andrew/.rbenv/shims
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: 764862464
  TOTALMEM: 17179869184
  UPTIME: 246966
  LOADAVG: 2.9423828125,2.64794921875,2.57080078125
  CPUS:
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  - Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz - 3100
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.4
  - openssl: 1.0.2p
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed: git -c core.safecrlf=false add "." && git commit -m "rebuild"

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed: git -c core.safecrlf=false add "." && git commit -m "rebuild"

  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed: git -c core.safecrlf=false add "." && git commit -m "rebuild"

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

=================================================================================

</details>

**Comment by sir-dunxalot** [comment]
I don't have any definitive evidence but this could be related to Node versions. I experienced this issue with node `v8.11.4` but a colleague, after switching to node 6, didn't experience it.

Here is an error trace for a machine that met this error (it is not very helpful):

```
=================================================================================

ENV Summary:

  TIME: ...
  TITLE: ember
  ARGV:
  - /usr/local/bin/node
  - /usr/local/bin/ember
  - github-pages:commit
  - --message
  - 3 release
  EXEC_PATH: /usr/local/bin/node
  TMPDIR: /var/folders/x3/bgrvx4j152q8cfc22k9zwvph0000gn/T
  SHELL: /usr/local/bin/zsh
  PATH:
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  PLATFORM: darwin x64
  FREEMEM: ...
  TOTALMEM: ...
  UPTIME: 2288390
  LOADAVG: 2.62353515625,2.7265625,2.55712890625
  CPUS:
  - ...

  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 32.0
  - http_parser: 2.8.0
  - icu: 60.1
  - modules: 57
  - napi: 3
  - nghttp2: 1.32.0
  - node: 8.11.4
  - openssl: 1.0.2p
  - tz: 2017c
  - unicode: 10.0
  - uv: 1.19.1
  - v8: 6.2.414.54
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Command failed: git -c core.safecrlf=false add "." && git commit -m "3 release"

  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Command failed: git -c core.safecrlf=false add "." && git commit -m "3 release"

  - name: Error
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: Error: Command failed: git -c core.safecrlf=false add "." && git commit -m "3 release"

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

=================================================================================
```
